on: [push]

jobs:
  swagger:
    runs-on: ubuntu-latest
    name: A job to do some go commands.
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2
    - name: go action
      id: go-action
      uses: ./
      with:
        test_dir: './'